---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: unifi
  name: unifi-controller-configmap
  labels:
    app: unifi-controller
    app.kubernetes.io/app: unifi-controller
    app.kubernetes.io/project: unifi
data:
  system.properties.default: |+
    ## system.properties
    ##
    debug.device=info
    debug.mgmt=info
    debug.sdn=info
    debug.system=info

    is_configured_and_restarted=true
    is_default=false

    reporter-uuid=<YOUR_REPORTER_UUID>
    uuid=<YOUR_UUID>
